# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a7b090a2b0e1e43022a825e9287cbc59454503449fc6823b8d0ee3e1c3a5c1381a1a8f1acd75fd6e3c34ecb1f853fae42d9256db41d951dc3213509bfff5e79

test:
  secret_key_base: 57310f5940bda5485572e10c2fe3d982a9cb44a1362c0aa3c51c9373bfdcc4f1ddd51fbab45f12a2bc25e83a0567a6ea08fb267fb74af31b88c5458c8905273e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
